### ISSUE TITLE
Testing examples jsbin failing - emq is not defined

### ISSUE THREAD

**Issue by kgish** [emberjs/website#1974]
I noticed that all of the jsbin examples in the website chapter on testing are failing:
```
global failure (1, 0, 1)Rerun1 ms
Uncaught ReferenceError: emq is not defined
Source: 	
http://null.jsbin.com/runner:42
```
Not sure if they are related but also recently having problems with my ember-cli integration tests failing as well with `ember_qunit` undefined for some reason.

**Comment by ryanmurakami** [comment]
I just put in a pull request to fix all the tests.
The issue was that the ember-qunit project moved to 2.0+ which removed the emq object. Most of the usages for emq have been made redundant, so you might just be able to remove any references to it from your ember-cli tests and it may work. Otherwise, you might investigate more here: https://github.com/rwjblue/ember-qunit

**Comment by trek** [comment]
We've migrated to versioned guides at https://github.com/emberjs/guides and no longer use JSBin
