### ISSUE TITLE
Start page mesage

### ISSUE THREAD

**Issue by MajorBreakfast** [emberjs/website#2045]
I just noticed that the download link and version indicator disappeared in favor of ember-cli instructions.

- version should be on the front page
- Wrong message: ember.js works without ember-cli. It's not the only way to use ember.

**I don't want ember to become a fully integrated development environment like meteor.** However, the message on the start page shapes how we think about ember. I'd prefer to think about ember as a browser-side javascript framework without any build requirements that will eventually integrate with the browser's standardized system module loader. It should never require a development environment beside a text editor. What I'd like is ember to represent itself as such a library foremost and that includes download links to JavaScript files. I've nothing against replacing the ember starter kit link with ember-cli download instructions. But the way it is now, I don't see how, by looking at the start page, a newbie could tell that ember works without ember-cli. Somewhere it should be mentioned that the core library is browser-side-only.

@jgwhite @stefanpenner and others
Related PR https://github.com/emberjs/website/pull/2044

**Comment by jgwhite** [comment]
@majorbreakfast all really good points.

@tomdale @wycats what are your thoughts?

**Comment by locks** [comment]
The guides are in the process of being rewritten for ember-cli. @MajorBreakfast your expectation does not align with Ember' happy path as best as I can tell. It is almost impractical to build a modern web application, especially at the ambitious scope that Ember is aiming to, without some sort of build pipeline.

It will be possible to use Ember outside of ember-cli of course, but the website experience will be focused on it. You can help provide documentation on non-ember-cli uses for the rewrite: https://github.com/emberjs/guides/issues/9.

There are numerous advantages to having a build pipeline: tree shaking of unused code, template pre-compilation, ember-cli addons, linting, testing, uglification, minification, ES6 transpiling. These are very important in non-trivial applications for performance and footprint reasons, as well as developer ease.

**Comment by tomdale** [comment]
What @locks said. Using Ember without Ember CLI leads to a severely degraded experience. Let's just own the fact that people who try to use Ember without Ember CLI tend to have a bad time, and those who use the two together have an amazing time. It might turn some people off, but those people would probably be better served by a less opinionated tool anyway.

**Comment by RyannosaurusRex** [comment]
Totally agree.  Even *with* Ember CLI, I actually had a really easy time integrating Ember into my ASP.NET.MVC app that gets auto-built with TeamCity than other frameworks.  Plus, the "blessed" stack means people answering my questions online are familiar with my stack because it's also their stack most likely.  I agree I don't want it to end up like meteor at all, but I don't think that's what's happening.  broccoli, Babel, and all the other parts are totally independent and from what I've seen look like they can be swapped out if needed.  Ember CLI just means the zero to 60 is fast, but you can still offroad if you want.

I do mostly "enterprise" work, and Ember is the first Js framework of the big ones that I've had interns and junior devs work on the project and not totally go off the rails have to babysit a bunch.  The opinions and tools to support it in Ember CLI really do make things way more productive and happy for everyone involved if the situation calls for it.

**Comment by MajorBreakfast** [comment]
ember-cli is the happy path, that's right.

But: **I want competition**

ember-cli in its current form is not the ultimate solution. I helped create ember-cli in its early days and know about some dirty stuff under hood. Many design decision that were made are good, but some are also bad. I stopped working on ember-cli because it took up too much of my spare time. But from the time I heavily participated in the project I learned one thing: You can't prototype completely new ideas in a project that other people use in production. If you try a new approach, then things break. An with "new approach" I mean using another build tool instead of broccoli or the like. So, I'm not talking about incremental features, but drastic changes which nonetheless deserve to be tried out. Here are some areas the come to mind:
- The addon system: The current addon system requires about a thousand files in the addon repository. I've never seen an ember addon that had just two files: A `package.json` and a `addon.js`. Sure, you need unit tests and more, but I really think that the current approach is a bit on the heavy side.
- The module loader: AMD is old. The module loader should be the [es6 module loader polyfill](https://github.com/ModuleLoader/es6-module-loader) because that's the future. Currently you can't load stuff dynamically, like `System.import('module').then()`. The architecture doesn't allow it.
- The package manager: Is bower really what we want? I kinda like jspm. Unless they improved it since, the `package.json`'s `main` field, that designates the main module, doesn't work reliably with bower modules like it does with npm modules.
- The build system: Broccoli has several issues. No source map support. No easy visualization of the pipeline. No parallel execution. And some other issues ([my list](https://gist.github.com/MajorBreakfast/e9bf6840952bd4257ea9)). I believe that broccoli the way it is now is not the perfect build system solution. @joliss had many great ideas, but she couldn't continue working on the project full-time like she did in the beginning. And the [commit history](https://github.com/broccolijs/broccoli/commits/master) proves that the project stagnates.

Can the ember-cli project try any of these new approaches? I think it might be barely possible to try the second one, the module loader, but the other three would be hell. They'd basically break every single addon. But I really think that these things should be tried out because they're worth it. Telling everyone to use ember-cli doesn't make that happen. Other build pipelines should get a chance. It would be much better if the core team continues to market ember as a browser-side JavaScript framework. It could still recommend ember-cli, but not as the only way to use ember. ember.js is not the library that is used internally by ember-cli, it's foremost a frontend JavaScript framework and ember-cli is A, not THE, way to build ember apps.

Instead, a real effort should be made to define more properly how build tools interact with ember.js. One of the main things ember-cli does is assembling the application by registering all the modules it finds in the folder structure. What it basically does is create a definition like this:
``` JavaScript
import ...

var App = Ember.Application.extend()
App.initializer({
  name: 'Register modules',
  initialize(container, application) {
    application.register('router:main', Router)
    application.register('route:blog-post', BlogPostRoute)
    application.register('component:blog-post', BlogPostComponent)
    ...
  }
})
```
It's a bit hidden because it achieves this using an alternative resolver. But when it comes down to it this is what ember-cli basically does. There is no reason why other build tools couldn't do this kind of job. There is no magic behind this. Yes, ember-cli does more, much more in fact. But it's not perfect and until it is it should be the first thing that comes to mind when we talk about ember.

**Comment by RyannosaurusRex** [comment]
Excellent points, @MajorBreakfast.   I always assumed the intent of Ember CLI was also to be able to swap out parts, like use TypeScript instead of Babel, or whatever else in the pipeline.  I know Ember CLI is still pretty young, but if those assumptions aren't correct that parts can be swappable, then I'm not sure requiring broccoli or whatever else is the correct approach, either.

I love Ember's generators, those are great, but do wish I could just use Grunt.  Was there ever a look at just using yeoman or something

**Comment by locks** [comment]
If you want competition, you can provide it. The Ember teams are small considering the size of the project, so they can't afford to compete with themselves, hence the happy path. If you document both the process and how to use your solution then everyone comes out even a bigger winner. There are already alternatives like https://github.com/yeoman/generator-ember. 

The ember-cli team knows the project is not final yet, hence it not being `1.0.0`. As for "If you try a new approach, then things break.", that's what semver is for. CLI `0.2.0` changed how addons work for example. As for the problems you listed, the current ways to address them are: submit an issue report; submit an RFC; submit a Pull Request.

Don't forget that global-style is going away as well.

**Comment by rwjblue** [comment]
>  I want competition

I would absolutely **LOVE** competition!!! Make sure to let us know what you come up with!

> I've never seen an ember addon that had just two files: A package.json and a addon.js

An addon only needs `package.json` and `index.js` (or whatever your main entry-point is).  https://github.com/ember-cli/ember-cli-uglify is pretty close to this (it also has a readme and license file) to show that it is absolutely possible.

> The module loader: AMD is old. The module loader should be the es6 module loader polyfill because that's the future. Currently you can't load stuff dynamically, like System.import('module').then(). The architecture doesn't allow it.

Old is not a reason to not use a thing, Ember is "old", JavaScript is "old", etc.  The entire pipeline in Ember CLI is kept as ES6 throughout the build process, and swapping a different loader is not precluded.  I would love to work with you on ensuring that we are ready for the future, but I believe that we are well positioned here.

> The package manager: Is bower really what we want?

No, and we plan to remove it.

> The build system: Broccoli has several issues. 

Show me a build system that does not have issues. :troll:

> No source map support.

Correct, broccoli does not have source map support.  This is because it does not need built in support, as it can (and is) provided by individual broccoli plugins as needed. Ember CLI ships with fairly decent source map support, and it will continue to get better.

> There is no reason why other build tools couldn't do this kind of job.

I completely agree, and look forward to your effort fleshing out these ideas!

---

Regardless of its foibles and flaws, ember-cli is still the easiest tool to use to get a new Ember app started.  When that is no longer true, we can easily change the details on the homepage.

**Comment by MajorBreakfast** [comment]
@rwjblue I like those intentions :) ATM I'm just prototyping, but there's a good possibility that I'll come up with an alternative solution. At this stage most of my ideas exist only on paper, though.

Back to this issue: What about bringing back the version indicator?
Maybe all three? `ember 1.10.0, ember-cli 0.1.15`

Maybe it could be automated:
https://api.github.com/repos/ember-cli/ember-cli/releases/latest
https://api.github.com/repos/emberjs/ember.js/releases/latest

**Comment by rwjblue** [comment]
It doesn't need to be automated, I agree that the homepage should report the current Ember version.

**Comment by MajorBreakfast** [comment]
Reporting ember-cli and ember versions separately also solves this issue because it directly shows new users that the cli is not ember itself.

**Comment by ulisesrmzroche** [comment]
-1. This is a massive selling point of Ember right now. I guess for people with side-projects or still in college, this would matter more, but as a consultant, this decision would probably kill me.

**Comment by ulisesrmzroche** [comment]
Basically, Ember CLI is the difference between a 40 hour workweek and a 60 hour work-week in large-scale, Ember Apps. This is too good to be true and should be kept that way forever.

**Comment by MajorBreakfast** [comment]
@ulisesrmzroche Are you disagreeing with the version indicators?

Two version indicators are good for the reasons explained above. It's true that I also started this issue to tell the core team that they shouldn't bar the way for ember-cli competitors. But that won't hurt ember-cli.

**Comment by rwjblue** [comment]
As discussed above, the landing page will continue to suggest the best way to get started with Ember. At this point, that is very clearly via ember-cli.

This issue has gone very far afield from @MajorBreakfast's initial intent (I believe), so I am closing it.

@MajorBreakfast - I would gladly accept a pull request showing both version numbers (in addition to showing how to npm install ember-cli).
