### ISSUE TITLE
Jsbin examples broken

### ISSUE THREAD

**Issue by ohcibi** [emberjs/website#2126]
Almost all jsbin examples in the guides are broken. Sometimes because they require the "latest" ember version (which then fails because the example was made before one needed to also require the ember-static-template-compiler), sometimes there are some internal errors which are not that obvious. Examples should always require a fixed version of all libraries they are using.

**Comment by vire** [comment]
@ohcibi please see https://github.com/emberjs/guides/issues/72 for more info.

**Comment by jrhorn424** [comment]
@vire @trek Can I help with this? Is the idea to move to Ember Twiddle? If you just need someone to update script tags, I can do that, too. 😄

**Comment by acorncom** [comment]
This issue was addressed in the guides repo a few months back, closing now.  @jrhorn424 if you're interested in helping out, we'd love to get your help over there :+1:  We've been trying to avoid putting in Ember Twiddle links in the guides though, as maintenance of them gets really complicated in the long-run ...
