### ISSUE TITLE
Improve search results by displaying results from api, blog posts and guides separately

### ISSUE THREAD

**Issue by szimek** [emberjs/website#2213]
I'm not sure if it's possible with Swiftype, but it would be really great. 

I was looking for a way to scroll page to the top on route transition, but only if the previous and the next route are not from the same "section". I found info about `Route` and its `willTransition` event and that `Transition` object is passed to the handler. However, finding any info about `Transition` object itself in docs or using search is impossible. If I type "transition" into the search box, I get links to blog posts and guides, but I can't see anything related to API docs. Maybe this object is not documented, but if the search results were separated, it would be much easier for me to find out.

**Comment by eccegordo** [comment]
yes, this would be very nice. Most of the time search is basically useless for me because I am trying to find something in a specific context such as API docs, and results from other contexts get in the way.

Breaking apart where the search results come from or even where you want to search would be very handy.

I am wondering if you could do something with keywords kind of like the old google search by site. e.g.

```
willTransition site:blog
willTransition site:guides
willTransition site:api-docs
willTransition site:web
etc
```

**Comment by acorncom** [comment]
I like this idea.  The guides repo is currently getting far more attention, so I'll move this over there for further discussion.
