### ISSUE TITLE
It appears that toggling inherited checkbox enables private members in api docs

### ISSUE THREAD

**Issue by petey** [emberjs/website#2264]
Here's a test case for you:

* Navigate to http://emberjs.com/api/classes/Ember.ArrayProxy.html
* Click on the checkbox labeled inherited
   * All methods disappear
* Click on checkbox labeled inherited
   * More methods appear than existed before (includes private methods)

**Comment by stefanpenner** [comment]
relevant HTML: https://github.com/emberjs/website/blob/master/source/_api_options.html.erb
relevant JS: https://github.com/emberjs/website/blob/59837b08c5bbcbe6579094e78c4f0d15d0139a17/source/javascripts/app/api/api.js

**Comment by chriskrycho** [comment]
This comes up because of an overlap between the types. Some elements are *both* `inherited` and `private`. The toggle behavior does not distinguish between them; it just toggles the value for *every* `inherited` member, and that includes some `private` members. (Notably, not all: if you go ahead and click the Private checkbox, you'll see that the non-inherited private members appear.)

Where is the index list implemented?

**Comment by ATMartin** [comment]
I may have a fix for this but I'm juggling an old bad commit upstream of my fix. Will be just a few on the PR for review.

**Comment by MaximAbramchuck** [comment]
@stefanpenner need to close this one.
