### ISSUE TITLE
404 for http://emberjs.com/api/classes/Ember.ArrayController.html

### ISSUE THREAD

**Issue by tkemperman** [emberjs/website#2434]
The link at https://guides.emberjs.com/v1.10.0/controllers/representing-multiple-models-with-arraycontroller leads to http://emberjs.com/api/classes/Ember.ArrayController.html which renders a 404.

**Comment by rwjblue** [comment]
The ArrayController API docs are no longer available (since Ember 2.x does not include ArrayController). The 1.10 guide link was correct, but now is not. I'm not sure what we can do about this (the past guide versions are essentially static).

**Comment by locks** [comment]
Like @rwjblue said, old versions of the guides are basically immutable, and since versioned API documentation viewer is still upcoming there would be no way to link to older API docs.

I'm closing this for now and when versioned API docs land we'll revisit the issue at https://github.com/emberjs/guides.
