### ISSUE TITLE
Ember-Data download does not work

### ISSUE THREAD

**Issue by cbou** [emberjs/website#2453]
All the link for downloading EmberJS Data are broken on this page: http://emberjs.com/builds/#/release

http://builds.emberjs.com/tags/v2.3.0/ember-data.prod.js
http://builds.emberjs.com/tags/v2.3.0/ember-data.min.js
http://builds.emberjs.com/tags/v2.3.0/ember-data.js

Beta and Canary are working.

**Comment by bmac** [comment]
I've fixed the build issue that was preventing tagged builds from being published to s3 by cherry-picking https://github.com/emberjs/website/issues/2453 to the released branch. They should be published again with Ember Data `v2.3.2`. 

However, I don't have the the access keys needed to manually republish the v2.3.0 builds to s3. If @rwjblue or @fivetanley have time maybe they can manually publish those builds. Otherwise, I likely release `v2.3.2` at some point today and update the releases page to point to the new build.

**Comment by bmac** [comment]
`v2.3.0` has been republished to S3.
