### ISSUE TITLE
Docs update

### ISSUE THREAD

**Issue by amurchick** [emberjs/website#2581]
On page http://emberjs.com/api/classes/Ember.Application.html 
```
To learn more about the advantages of event delegation and the Ember view layer, 
and a list of the event listeners that are setup by default, 
visit the Ember View Layer guide.
```
link in phrase `Ember View Layer guide` points to https://guides.emberjs.com/v2.5.0/understanding-ember/the-view-layer/, but 404 error happens.

Old worked link was http://guides.emberjs.com/v1.11.0/understanding-ember/the-view-layer/#toc_adding-new-events

**Comment by acorncom** [comment]
@amurchick This is actually generated from API documentation in the headers of the appropriate files in emberjs/ember.js  Would you mind sending in a PR over there to remove the link (and possibly edit the text)?  Views don't exist in 2.x, which is why the guides page was removed ...  I'll close this here for now ...
