### ISSUE TITLE
Introduce an "Online" category for meetups

### ISSUE THREAD

**Issue by dgeb** [emberjs/website#2641]
We should have a category for online meetups not tied to a particular lat/long.

Re: https://github.com/emberjs/website/pull/2371

**Comment by wifelette** [comment]
I initially had a suggestion for that; the issue was closed due to inactivity, I think the assumption was that the folks talking about it at the time lost interest. At the time it was the best idea I could come up with, and there haven't been better suggestions since.

That said. With the growth of the online conf phenomenon, the online video lecture series concept, online trainings, things like that, I'm no longer convinced something like this _belongs_ on the Meetup page. 

It likely belongs _somewhere_, but as of right now we don't have a location that helps promote online content, video, podcast or otherwise. I'm leaning more towards online content being a completely different thing than in-person groups/events/activities. Indeed, so far the only thing on this list that we have infrastructure for is the first item: in-person groups. 

We've done well, in our simple way at least, for in-person groups, and it's been helpful for the network effect and fostering in-person community. We should ponder similar ways we can help other types of initiatives, and be patient with what limited bandwidth exists :)

We also need to ponder the marketing ways in which online content is different. People rarely if ever experience spam related to routinely meeting in person, but it's much easier to go a different route when it's about SEO, traffic and clicks. In-person meetups are also rarely profit-oriented operations, and that's not necessarily the same with all online content (could go either way online, especially where more commercial training is concerned). 

This merits serious consideration; we know our community is sensitive to over-promotion and we should figure out how we can help online efforts, without running the risk of being affiliated with that sort of thing when it goes awry. Something as simple as our Meetup listing but for online stuff is probably the best option, maybe categorized functionally in a similar way to Meetup locations. Needs more thought and brainstorming 👍  

I'll chat with the Learning Team about it. To set correct expectations, we're pretty swamped with the existing website work. But there's always room in the queue for more _future_ work :D

**Comment by dgeb** [comment]
That all makes a lot of sense to me, @wifelette. You've clearly thought a lot about this issue, which borders on many others. 

I agree that the Meetups page should not feature any for-profit, commercial events. I'm pretty sure this would feel misleading, given the common expectation that meetups are non-profit, community-driven events. I suppose there could be a place for an online meetup that is non-profit and not commercial in any way.

It strikes me that we could setup something similar to the job board for online resources of all kinds, including for-profit content, training, and conferences. And of course I appreciate that this will take quite a bit of thought and planning to get right.

Please feel free to close, rename, or break up this issue as you see fit. Thanks in advance to you and the rest of the Learning Team for considering how to best address all of this :)

**Comment by ultimatemonty** [comment]
Would it be useful to have a Resources section? We have something similar on the [Atlanta Ember](http://www.atlantaember.io/resources#/resources) that could be a good fit. It could live on the existing Community page. Maybe a 3rd section called **Want to learn more?** at the bottom along with **Join a Meetup** and **Meet Tomster**?

**Comment by locks** [comment]
Will re-open if the concept is revisited.
