### ISSUE TITLE
Korean Translation

### ISSUE THREAD

**Issue by adisonjames** [emberjs/website#2981]
Hi,

I work at a company in Korea that currently builds a web application using ember. 
I am the Technical Project Manager and would like to translate the 5-minute Getting Started Guide and as time and resources permit, eventually the entire tutorial.

I have used Ember to build my own personal projects in addition to the current e-commerce application being built by the company I work for, and I also have extensive experience with Korean and English translations.

Could you point me to the best-practice to start working on translations?

I plan to begin this week and hope I can contribute this resource for all to share.

Thank you,
adisonjames

**Comment by jenweber** [comment]
Hi @adisonjames , thanks for offering to do a translation and make Ember accessible to more people! My recommendation is to make the translation available via a blog article or video tutorial. This has a few benefits over directly adding a translation to the site.

First, this sidesteps the major barrier of rewriting the site architecture. Unfortunately we don't have the infrastructure yet to support translations. We had some automated tools in the past, but even they were discontinued due to lack of time and resources.

Secondly, an article/video would not require endless updates. There were 23 pull requests merged in the guides over the last month alone. However, I definitely reference older community articles/tutorials to do my work, and I expect that some content will be out of date. It's ok.

I think many people can benefit from your translation, especially the quick start. I hope you'll consider still writing it.

I don't know of any best practice resources myself, but you could ask on Ember Slack. There are people from all over the world and I bet someone has done something similar for another language.

**Comment by adisonjames** [comment]
Thank you for your reply. I will follow your guidelines and work on the
translation locally.

James Chung

**Comment by aureliosaraiva** [comment]
@adisonjames 
The Ember-Brasil community is making an effort to translate the entire content of the Ember Guide unofficially.

The translation will be made a new repository in github, after a part will be translated we will publish as an article / post in the medium.com of the Brazilian community.

The idea is that when we have a considerable content translated, we will create an unofficial site ember-brasil.com.br to make the content available in a unified location.

We do not know yet if this is the best way, but let's experiment and see if we get results.

I hope I have contributed something. I am at your disposal.

**Comment by adisonjames** [comment]
@aureliosaraiva 
cc: @htkim

That is great news. If we could start a series of i18n translations for Ember on Github I would like to participate contribute. We could link to each other's repos and domains as well.

Let's keep in touch (I have still yet to start on the translation, but will do so this week).

**Comment by locks** [comment]
Thanks for the discussion, and good luck!
I'm closing the issue for house keeping, but let us know on Slack if we can help with anything.
