### ISSUE TITLE
Better user showcase

### ISSUE THREAD

**Issue by sandstrom** [emberjs/website#3045]
@wifelette Would you be open to updating the 'user showcase' with more well-known companies? 

A good list of example users will help with adoption and when developers need to talk managers etc. into using a particular framework ("Zendesk is using it, it will work").

The current list:

- MHE Labs => Never heard of
- Yapp => Never heard of
- Tilde => We're a happy Skylight customer so I know, but it's not a global brand (sorry! 😄 )
- Bustle => Never heard of

Instead, I'd suggest these four:

- **Netflix** (well known consumer company)
- **Intercom** (ambitions Ember app + easy to create an Intercom account and play with it)
- **Zendesk** (good enterprise example)
- **Heroku** (have solid reputation among developers)

A few other good examples (but I'd still vote for the four above):
- Kickstarter
- LinkedIn
- Travis CI
- Square

***

Someone said this PR is "rude" because the companies listed on top has contributed heavily to Ember's success. I don't mean to belittle anyone. But I think it makes more sense to highlight well known companies, to help drive Ember adoption. There are other ways to give credit to contributors.

FWIW my own company used to be prominently displayed in that list (we were ~5th), and has since been moved down. I don't think that's rude to us — on the contrary it made sense to replace our (relatively unknown company) with more recognisable logos.

**Comment by rtablada** [comment]
I think a general discussion of keeping the users and advertising up to date is something we should do better at.

However, the thought of highlighting some companies over others is short sighted IMO.

I think a big benefit of having a lot of different types of companies is that it shows Ember can be used in different situations.

---

In terms of companies to include I think there is a discussion of who we would like to contact, but there is legal and marketing hoops to go through in order to get approval to use company assets to market ember.

**Comment by NullVoxPopuli** [comment]
I think it depends on what you know. From the list, my most well known are (in order):
Twitch, Acorns, NetFlix, Microsoft, TED, LinkedIN, testdouble, Travis CI, Yahoo, thoughtbot, Boxee,  Urbanspoon, Discourse, Square, ZenDesk, TinderBox,

**Comment by acorncom** [comment]
From what I remember, we've discussed this before.  I know we're potentially playing with 🔥 here (and so think we should tread cautiously), but I think there is merit in the discussion.

Most scrappy startups have a "look who else is using us!" section (like we currently do on the website) but they deliberately cherry-pick well-known brands if at all possible.  Neither the React nor the Angular website do this, but that's because React and Angular are well-known as tools with mammoth companies behind them.  One of Ember's main pitches is that we've adopted a "coalition-led" approach to OSS.  Given that, I think it's worth thinking through how to highlight well that that coalition approach has worked (and is still working) for us.

Politically, I can see this getting complicated.  But I still would like to see us consider how to improve it so that Ember isn't considered an also-ran in the JS world ... 😀

**Comment by sandstrom** [comment]
@rtablada All companies I mentioned are either in the 'top four' front page list or among the [list of ember users](https://emberjs.com/ember-users/). So it's only a matter of prioritization — no need to ask any legal/marketing departments.

@NullVoxPopuli Agree, it depends (I'm not American, for example). I'm not very fixed on a specific set of companies, as long choose good examples.

I'd say a balance between recognizable, different industries and different types of applications. So some consumer application, something B2B and tilted towards companies that developers will know about (sorry Bustle!, hehe).

**Comment by wifelette** [comment]
Heya—

I'm on board for a refresh, it's time. I used to do it periodically but haven't in a while. So thanks @sandstrom for bringing it back up!

We did some tidy-work on #3011, and talked about design changes in #2973. I'm still on board for the changes we theorized in #2973 but I don't think we have design resources to work on it. Also, there's no reason this should gate on that, but I wanted to make sure all the context was here :)

I'll get a new PR in today to at least make some starter swaps for bigger names. But I'd love to have someone tackle a design like #2973 if someone's up for it, and am still game to get in touch with the companies for authorization if the design materializes.
